name: catching_josh
description: "A Flutter package that makes try-catch operations elegant and customizable with clean error logging and flexible error handling options."
version: 1.1.0
repository: https://github.com/joseph-seph88/catching_josh

environment:
  sdk: ^3.6.0
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
